#配置根目录和访问端口
server:
  port: 8055
  servlet:
    context-path: /draw
    session:
      cookie:
        max-age:

spring:
  # 配置数据库1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/draw?characterEncoding=UTF-8&useUnicode=true&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: root
    #password: MyNewPass4!
